# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime, timedelta
from typing import Any
from typing_extensions import Self
import base64
import datetime
import os
import subprocess
import threading
import time
import wmi

def __KillProcessByPid(pid: Any) -> Any:
    ...

def __Exit() -> Any:
    ...

class Recorder:
    def __init__(self: Self) -> None: ...
    def update(self: Self) -> Any: ...

def __GetWMIC(cmd: Any) -> Any:
    ...

def __GetCpuName() -> Any:
    ...

def __GetCpuId() -> Any:
    ...

def __GetDiskNum() -> Any:
    ...

def __GetDecrypt(data: Any, key: Any) -> Any:
    ...

def __GetEncrypt(data: Any, key: Any) -> Any:
    ...

def __GenLicense() -> Any:
    ...

def __GetMark(code: Any, byteArray: Any) -> Any:
    ...

def __LicensingCheck(code1: Any, code2: Any) -> Any:
    ...

def __LicensingGetTime(code: Any) -> Any:
    ...

def __LicensingRemoveTime(code: Any) -> Any:
    ...

def __LicensingByStr(code: Any, timeDay: Any) -> Any:
    ...

def __LicenseGenByStr() -> Any:
    ...

def __LicensingUpdateTime(code: Any) -> Any:
    ...

def __LicensingAddTime(timeDay: Any, code: Any, mask: Any) -> Any:
    ...

def __LicensingByStrTest(code: Any, timeSecond: Any) -> Any:
    ...

def __LicenseUpdate(path: Any) -> Any:
    ...

def LicenseCheck(path: Any, company: str = "HRVision",
                 project: str = "", is_registry: bool = True) -> int: ...
    ...

def RegisterLicenseFailed(callback: Any, user: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import subprocess
import time
import base64
import datetime
import os
import threading